Repository BOSWatch/BW3-Core, pull requests merged in 2020-04, with the labels that each got.

#27 Create install.sh
  install.sh
Labels: Component: Client, Component: Server, Feature

#33 fix docu zvei->tone
  docu/docs/modul/descriptor.md
  docu/docs/modul/regex_filter.md
Labels: Enhancement, Status: Review Needed

#36 Pytest 3.8
  .github/workflows/run_pytest.yml
Labels: Status: Review Needed

#34 Add Fix for descriptor, resolves #31
  module/descriptor.py
Labels: Bug, Status: Review Needed

#32 add descriptor unit test
  test/module/test_descriptor.py
  test/pytest.ini
  test/test_config.yaml
Labels: Bug, Unittest

#35 add workflow to build documentation
  .github/workflows/build_docs.yml
Labels: Status: Review Needed

#38 Neue InputSource - LineIn
  boswatch/inputSource/lineInInput.py
  bw_client.py
  config/client.yaml
  docu/docs/config.md
Labels: Component: Client, Feature, Status: Review Needed
